---
cookiecutter:
  #
  # TODO: Please pick one, e.g. command_line_interface: Click
  command_line_interface:
    - Click
    - None
  #
  # TODO: Please pick one, e.g. open_source_license: MIT
  open_source_license:
    - MIT
    - BSD
    - ISC
    - Apache
    - GNUv3
    - Proprietary

  #
  # These were guess based on the repository information
  # You probably want to customize them.
  project_namespace: "{{ cookiecutter.github_organization }}"
  project_slug: "{{ github.repository.name.lower().replace(' ', '_').replace('-', '_') }}"
  project_name: "{{ cookiecutter.project_namespace }}'s {{ github.repository.name }}"

  #
  # These are likely correct...
  anaconda_organization: "{{ cookiecutter.github_organization }}"

  #
  # These should not be changed at the moment...
  noarch_python: y
  use_pytest: y
  add_pyup_badge: y
  version: 0.0.0

  #
  # These should probably be left alone. They came from github
  full_name: "{{ github.author.name }}"
  email: "{{ github.author.email }}"
  github_username: "{{ github.author.username }}"
  github_organization: "{{ github.repository.full_name.split('/')[0] }}"
  project_repo: "{{ github.repository.name }}"
  project_short_description: "{{ github.repository.description }}"
