name: ght-renderer
on:
  push:
    branches:
      - master
    paths:
      - .github/ght.yaml
jobs:
  ght-render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 jinja2-cli jinja2-time pyyaml
      - run: |
          .github/bin/ght-render.sh render_tree_structure
          .github/bin/ght-render.sh render_tree_content
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ght/render
          branch-suffix: none
