name: ght-init
on:
  push:
    branches:
      - master
jobs:

  create-issue:
    runs-on: ubuntu-latest
    steps:

  ght-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2 jinja2-cli jinja2-time pyyaml

      - name: Create GHT Branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: ght/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Create protect branches issue
        uses: maxkomarychev/oction-create-issue@v0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Please protect the master and ght branches
          body: |
            Thanks for using sodre/ght-pypackage. These steps are hard to automate,
            and you only need to do them once...
              - [ ] [Protect][1] your `master` branch.
              - [ ] [Protect][1] the `ght/master` branch.

            [1]: https://github.com/${{github.repository}}/settings/branch_protection_rules/new

      - name: Create ght-repository.yaml file
        run: |
          cat > .github/ght-repository.yaml <<-EOF
          github:
            repository:
              name: ${{ github.event.repository.name }}
              full_name: ${{ github.event.repository.full_name }}
              description: ${{ github.event.repository.description }}
              private: ${{ github.event.repository.private }}
              owner:
                login: ${{ github.event.repository.owner.login }}
                email: ${{ github.event.repository.owner.email }}
          EOF
          sed -i -e "/$/r .github/ght-repository.yaml" .github/ght.yaml
          rm -f .github/ght-repository.yaml

      - name: Render ght.yaml configuration
        run: |
          .github/bin/ght-render.sh render_configuration

      - name: Setup workflows for rendering repository
        run: |
          git mv .github/workflows/ght-init.yml .github/workflows/available/ght-init.yml
          git mv .github/workflows/available/ght-render-repo.yml .github/workflows

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ght/configure
          branch-suffix: none
          commit-message: Add GHT configuration variables
          title: Configure GitHub Template Variables
          body: |
            You are almost there! Here is what is left to do...

              - [ ] Configure your [ght.yaml][1] file in this PR
              - [ ] Wait for the build to pass...
              - [ ] Merge

            [1]: https://github.com/${{github.repository}}/edit/ght/configure/.github/ght.yaml
