name: ght-init
on:
  push:
    branches:
      - master
jobs:

  create-ght-branch:
    runs-on: ubuntu-latest
    steps:
      - name: create post-generation issue
        uses: maxkomarychev/oction-create-issue@v0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Please protect the master and ght branches
          body: |
            Thanks for using sodre/ght-pypackage. These steps are hard to automate,
            and you only need to do them once...
              - [ ] [Protect][1] your `master` branch.
              - [ ] [Protect][1] the `ght/master` branch.

            [1]: https://github.com/${{github.repository}}/settings/branch_protection_rules/new

  ght-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create GHT Branch
        uses: peterjgrainger/action-create-branch@v1.0.0
        with:
          branch: ght/master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git rm .github/workflows/ght-init.yml
      - run: |
          echo "github:" >> .github/ght.yaml
          echo "  repository:" >> .github/ght.yaml
          echo "    name: ${{ github.event.repository.name }}" >> .github/ght.yaml
          echo "    full_name: ${{ github.event.repository.full_name }}" >> .github/ght.yaml
          echo "    description: ${{ github.event.repository.description }}" >> .github/ght.yaml
          echo "    private: ${{ github.event.repository.private }}" >> .github/ght.yaml
          echo "    owner:" >> .github/ght.yaml
          echo "      name: ${{ github.event.repository.owner.name }}" >> .github/ght.yaml
          echo "      login: ${{ github.event.repository.owner.login }}" >> .github/ght.yaml
          echo "      email: ${{ github.event.repository.owner.email }}" >> .github/ght.yaml
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ght/configure
          branch-suffix: none
          commit-message: Add GHT configuration variables
          title: Configure GitHub Template Variables
          body: |
            You are almost there! Here is what is left to do...

              - [ ] Edit/Configure yor [ght.yaml][1] file in this PR
              - [ ] Wait for the build to pass...
              - [ ] (Squash-and-)Merge

            [1]: https://github.com/${{github.repository}}/edit/ght/configure/.github/ght.yaml
